// This file has been moved to the data layer.
// Update imports in other files to reflect the new location.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcVELgWBZagolw1KcbD8o9rCT3Fuyzphg',
    appId: '1:380634079068:web:a0ccb5b799b2fe07c0ab99',
    messagingSenderId: '380634079068',
    projectId: 'unimet-proyecto-libros',
    authDomain: 'unimet-proyecto-libros.firebaseapp.com',
    storageBucket: 'unimet-proyecto-libros.firebasestorage.app',
    measurementId: 'G-5J4RKT7265',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnJQhFhsUYsB2kc_B8lSFMnUKsc2k9bX4',
    appId: '1:380634079068:android:19dfb2e7974ec285c0ab99',
    messagingSenderId: '380634079068',
    projectId: 'unimet-proyecto-libros',
    storageBucket: 'unimet-proyecto-libros.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-o5yK5vze8tem0HGoccU9LtxKZmrI44s',
    appId: '1:380634079068:ios:f82c06126762ab61c0ab99',
    messagingSenderId: '380634079068',
    projectId: 'unimet-proyecto-libros',
    storageBucket: 'unimet-proyecto-libros.firebasestorage.app',
    iosClientId:
        '380634079068-o82mb6i43uvaa285tn7sn2q8bvrlpu7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimetMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-o5yK5vze8tem0HGoccU9LtxKZmrI44s',
    appId: '1:380634079068:ios:f82c06126762ab61c0ab99',
    messagingSenderId: '380634079068',
    projectId: 'unimet-proyecto-libros',
    storageBucket: 'unimet-proyecto-libros.firebasestorage.app',
    iosClientId:
        '380634079068-o82mb6i43uvaa285tn7sn2q8bvrlpu7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimetMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcVELgWBZagolw1KcbD8o9rCT3Fuyzphg',
    appId: '1:380634079068:web:a715f2a74eaf6dd2c0ab99',
    messagingSenderId: '380634079068',
    projectId: 'unimet-proyecto-libros',
    authDomain: 'unimet-proyecto-libros.firebaseapp.com',
    storageBucket: 'unimet-proyecto-libros.firebasestorage.app',
    measurementId: 'G-J2Z60MW9HD',
  );
}
